### ISSUE TITLE
"Crown of the Woodland Realm" Court Artifact floats

### ISSUE THREAD

**Issue by JukeJukestar** [CK3RealmsinExile/RealmsInExile#1008]
![Image](https://github.com/jj248/RealmsInExile/assets/76008882/b67eb7a9-97d1-4f51-8117-c4e806a7fbd4)

**Comment by jj248** [comment]
I'll pick this one up.

**Comment by jj248** [comment]
@JukeJukestar - how do I even acquire this as a court artifact? :D

**Comment by BriceLeduc** [comment]
You get it as a result of taking the decision_desecrate_aradhrynd

**Comment by jj248** [comment]
Gotcha. Might be simplest to just use a more generic asset as for some reason I can't resale the model in a different position more appropriate for an artifact.

**Comment by jj248** [comment]
@BriceLeduc - suggesting we just revert the model to something vanilla?

**Comment by Hendrix1337x** [comment]
Closing this as it is fixed

![image](https://github.com/user-attachments/assets/e2294d01-194b-40ab-b0ae-54dd4e865dca)
