### ISSUE TITLE
Loremaster Appointment Issue

### ISSUE THREAD

**Issue by leadsupport** [CK3RealmsinExile/RealmsInExile#1123]
It is currently impossible to appoint a loremaster if the position is vacant. If the position is filled, it can be swapped without issue, but if no loremaster is appointed on game start or they are fired, it is impossible to appoint a new one. It doesn't seem to be a cooldown issue, rather that the game is not finding any valid candidates for some reason. 
![image](https://github.com/jj248/RealmsInExile/assets/127911521/cc5302ee-b3fd-4ba6-a408-315767f0d4a9)
![image](https://github.com/jj248/RealmsInExile/assets/127911521/136d30eb-1607-4260-9f3c-8e0f6f105b99)

**Comment by Jaco-Daan** [comment]
This has been fixed, closing
