### ISSUE TITLE
Rhudaur hillmen getting assigned random traits

### ISSUE THREAD

**Issue by Hendrix1337x** [CK3RealmsinExile/RealmsInExile#1141]
In the Angmar Start date It appears that nearly all of the children characters in Rhudaur are getting more than 4 traits, for most cases it looks like they haven't been assigned a "disallow_random_traits = yes" clause in the History files, some examples are provided below.

<details>
<summary>Click to Expand</summary>

![image](https://github.com/jj248/RealmsInExile/assets/154389264/05201b59-a4ea-4559-97e4-b23d198b76bc)

![image](https://github.com/jj248/RealmsInExile/assets/154389264/2683d5cf-2a91-42e4-889e-c64e51744980)

![image](https://github.com/jj248/RealmsInExile/assets/154389264/589d7de6-6662-4f4a-8754-3670cc419419)

![image](https://github.com/jj248/RealmsInExile/assets/154389264/33e68bbb-5449-4b79-9093-476d8fbffbe9)

![image](https://github.com/jj248/RealmsInExile/assets/154389264/696f00a7-6538-410b-9425-fbec58ded29a)

![image](https://github.com/jj248/RealmsInExile/assets/154389264/53893ee8-5d39-4998-87c3-74f970eda4ec)

![image](https://github.com/jj248/RealmsInExile/assets/154389264/52483510-3a3d-49ec-beec-6dd32d0e29f5)

</details>

**Comment by Trigparmandil** [comment]
Fixed
