### ISSUE TITLE
Missing mannish counties in custom_mannish_thani_hazad region

### ISSUE THREAD

**Issue by zeltron1** [CK3RealmsinExile/RealmsInExile#1142]
The mannish counties in Gimilthani and southern Drel are not included as mannish counties in Thani-Hazad
<details>
<summaryClick to expand</summary>

![Screenshot 2024-07-04 160220](https://github.com/CK3RealmsinExile/RealmsInExile/assets/174716755/bdabbac9-f9bf-4e60-8e5e-5a269a2d1fa0)

</details>

**Comment by Trigparmandil** [comment]
Fixed. I didn't add the other mannish duchy in Drell (d_metkharan), since this is for the NiE trigger, and I don't think those areas should be included
