### ISSUE TITLE
Iberian struggle in Forodwaith

### ISSUE THREAD

**Issue by zeltron1** [CK3RealmsinExile/RealmsInExile#1146]
The Iberian struggle is active in Forodwaith. It seems to be consistent between games.
<details>
<summary>Click to expand</summary>

![Screenshot 2024-07-07 143712](https://github.com/CK3RealmsinExile/RealmsInExile/assets/174716755/b08a7386-bff6-409f-8ad9-e35d154fe714)

</details>

**Comment by Jaco-Daan** [comment]
closing, appears to be fixed. Confirmed by both OP and Hendrix
