### ISSUE TITLE
Inaccurate descriptions for the "Release vassal as tributary" interaction

### ISSUE THREAD

**Issue by zeltron1** [CK3RealmsinExile/RealmsInExile#1147]
The description says that tributaries are permanent and client states are temporary while it is actually the opposite. The description also implies that protectorates pay tribute to their protector which is inaccurate.
<details>
<summary>Click to expand</summary>

![Screenshot 2024-07-07 190434](https://github.com/CK3RealmsinExile/RealmsInExile/assets/174716755/af54d132-0608-4595-baf2-d01f30d77775)

</details>

**Comment by Jaco-Daan** [comment]
The permanent/temporary has been swapped around and the `tributary` has now been changed to `protectorate` in the interaction window. 

Closing
