### ISSUE TITLE
Acquiring the Leader of the Balan-Lai title vassalizes you to the previous holder

### ISSUE THREAD

**Issue by goatbush** [CK3RealmsinExile/RealmsInExile#1156]
Playing as a duke, i was elected leader of the Balan-Lai and it immediately vassalized me to previous holder that was a king. 

<details>
<summary>click to expand</summary>

![image](https://github.com/user-attachments/assets/4bd2bed3-e931-4c86-90a4-3dbd07a609d3)

![image](https://github.com/user-attachments/assets/ffb7a0aa-e4e9-4143-8b05-a2210cc3d46d)

</details>

**Comment by Jaco-Daan** [comment]
Has been fixed, closing
