### ISSUE TITLE
Republican Arnorians wear orc armor

### ISSUE THREAD

**Issue by zeltron1** [CK3RealmsinExile/RealmsInExile#1160]
![Screenshot 2024-08-01 192534](https://github.com/user-attachments/assets/06fb060d-9581-4c72-b7bc-ec9c6de65b65)

**Comment by Hendrix1337x** [comment]
Closing this as it is fixed

![Image](https://github.com/user-attachments/assets/b607cdca-8752-4d65-91ad-f49717f75cd3)

![Image](https://github.com/user-attachments/assets/8c17b840-db0d-4a0b-b1f8-8d9035c0f37d)
