### ISSUE TITLE
Tom Bombadil has become a fully interactable character

### ISSUE THREAD

**Issue by zeltron1** [CK3RealmsinExile/RealmsInExile#1170]
![Screenshot 2024-09-12 184745](https://github.com/user-attachments/assets/8a03d4de-ac43-4dc9-af41-2e62908d7fdc)

![Screenshot 2024-09-12 184831](https://github.com/user-attachments/assets/c05fc897-c7e3-4f51-8464-da7538089b08)

**Comment by Trigparmandil** [comment]
Context?

**Comment by zeltron1** [comment]
It just happened

**Comment by zeltron1** [comment]
I don't know what could have caused it

**Comment by CK3RealmsinExile** [comment]
![20240913014947_1](https://github.com/user-attachments/assets/d4b6d3ee-cbd2-460b-825f-e27fafae39c0)
![20240913014946_1](https://github.com/user-attachments/assets/cf66b671-cd3a-4b19-9bce-156d54a7fbe8)
Seems fine to me? This is one the latest dev version

**Comment by zeltron1** [comment]
Weird

**Comment by leadsupport** [comment]
This has h

**Comment by zeltron1** [comment]
That's probably what's going on on my end

**Comment by zeltron1** [comment]
I will check and close if it works
