### ISSUE TITLE
Disabled holdings for Sauron/Nazgul

### ISSUE THREAD

**Issue by zeltron1** [CK3RealmsinExile/RealmsInExile#1175]
Might be related to whatever disables delvings for them

![Screenshot 2024-09-24 182934](https://github.com/user-attachments/assets/5a5597e0-3e60-48c4-a488-72fd840bfc8d)

**Comment by Hendrix1337x** [comment]
Closing this as it is fixed

![Image](https://github.com/user-attachments/assets/c72f11b5-6bf1-43ba-8a3f-56d04ec5efc2)
