### ISSUE TITLE
Probable History Errors - Missing liege 

### ISSUE THREAD

**Issue by zeltron1** [CK3RealmsinExile/RealmsInExile#1181]
Nethos was definitely not independent before
![Screenshot 2024-09-30 194323](https://github.com/user-attachments/assets/a72866cb-c248-4f65-8da2-5015cad7ab76)
The two Woodmen counties here are weird because they're independent but their rightful de jure liege exists with barely any territory in the duchy

![Screenshot 2024-09-30 194732](https://github.com/user-attachments/assets/0789be49-eab1-4de6-9cb9-b294969d061f)

**Comment by Trigparmandil** [comment]
Nethos, yes. 
Not sure on the woodmen

**Comment by RedArkady** [comment]
The Woodmen aren't an error, it was designed like that.

**Comment by Trigparmandil** [comment]
Fixed, closed
