### ISSUE TITLE
Its possible to create wilderness adventurers

### ISSUE THREAD

**Issue by zeltron1** [CK3RealmsinExile/RealmsInExile#1192]
By creating a custom adventurer, you can get wilderness culture and faith on your character since the default culture/faith for character creation is the same as the one of the ruler you selected to create the character, that being Tom and wilderness culture/faith in this case. Creating adventurers in the wilderness should be made fully impossible as it also leads to your camp starting off map in Tom's capital on top of the other issues.
<details>
<summary>Click to expand</summary>

![Screenshot 2024-10-11 205726](https://github.com/user-attachments/assets/e5b0dc41-3aa7-4f69-8ba5-5a0150132077)

![Screenshot 2024-10-11 210348](https://github.com/user-attachments/assets/c60ddcb1-911a-4ed8-8953-122a048076f4)

![Screenshot 2024-10-11 205735](https://github.com/user-attachments/assets/4af7ca6d-8653-46e7-beb3-c36f16b8b598)

**Comment by zeltron1** [comment]
A similar issue is also present in Valinor as its possible to create adventures and play as them there. I suspect that this is possible for all normally unplayable starts so if there are any other import ones to block than it should also be fixed there.![Screenshot 

<details>
<summary>Click to expand</summary>

![Screenshot 2024-10-11 210856](https://github.com/user-attachments/assets/30913ba9-1381-4b31-a9e4-393b72ad9960)

**Comment by Jaco-Daan** [comment]
Both of these issues have been fixed, just need to be tested/confirmed

**Comment by zeltron1** [comment]
Can confirm this is fixed
![Screenshot 2024-10-12 073700](https://github.com/user-attachments/assets/a7b149bb-7804-4300-8ca9-5ee7e5f1ab59)
