### ISSUE TITLE
Gondor starting out with Harandor vassalized

### ISSUE THREAD

**Issue by zeltron1** [CK3RealmsinExile/RealmsInExile#1204]
This was definitely not the case before.
![Screenshot 2024-11-10 105508](https://github.com/user-attachments/assets/3faeb361-f2f2-4e0c-aa5f-0126962521c3)

**Comment by Jaco-Daan** [comment]
This has been fixed. Closing

**Comment by zeltron1** [comment]
The bug is still there, though most of it is fixed
![Screenshot 2024-11-11 200345](https://github.com/user-attachments/assets/3a644c12-7d16-4170-90dc-bd8192b44253)
