### ISSUE TITLE
Give player led Eowyn the choice to lift her temporary celibacy

### ISSUE THREAD

**Issue by jj248** [CK3RealmsinExile/RealmsInExile#181]
https://discord.com/channels/751097183448727552/778645689089392730/871761060103847936

**Comment by jj248** [comment]
Will require a quick tweak to gondor.0302 - will pick up tomorrow.

**Comment by jj248** [comment]
Needs testing to ensure that it fires for a player controlled Eowyn and that the choices work as desired.  Also, anyone feel free to be more creative with the writing!

**Comment by Remerod** [comment]
It's working now! Closing the issue 

![image](https://user-images.githubusercontent.com/79544635/155861283-86045bc5-d101-432a-a542-f1eef173af75.png)
