### ISSUE TITLE
3D Sugestion: Looks & Styles for lotr Thrones

### ISSUE THREAD

**Issue by Remerod** [CK3RealmsinExile/RealmsInExile#297]
**Introduction**
So mainly making this suggestion issue for suggestion & recommendations for Thrones as of now in **Royal Court** you can have different ones, as they both exist as generic ones and as special artifact ones
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/154411068-25097e85-eccd-46d1-80a0-66c178be740c.png)

</details>

# Suggestions for 2.3 available Content

So with upcoming 2.3 there will be several court rooms available, the suggestions here will mainly cover them.

**Gondor**
So as our only custom made courtroom made Gondor already have a throne, so maybe they are the least in need for one! But it doesn't hurt to have several for variation i guess.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/154411395-46352245-8525-4c3e-80f3-bd008f309a9e.png)
Our Current Existing Throne. Already fabulous! 

![image](https://user-images.githubusercontent.com/79544635/154411549-585a3e3f-62ef-49f4-8aeb-9e8ffcdaf35e.png)

![image](https://user-images.githubusercontent.com/79544635/154411605-a8e4b2e2-721f-4218-9b3d-bb4fae4734be.png)
The Movie set for the Minas Tirith throne room and thrones, both backs and fronts.

![image](https://user-images.githubusercontent.com/79544635/154411674-3c5cf441-fa9f-484e-ab9d-1219caa6ec88.png)
Minas tirith throne room made by the Artist [Hayo Koekkoek](https://www.artstation.com/ezykeyal) Several viewpoints can be seen on this website and source of image: https://www.artstation.com/artwork/gBX3Z 

![image](https://user-images.githubusercontent.com/79544635/154411944-7c2c11f6-7b3c-485c-87c0-4207eb972501.png)
So in LOTR: Rise of War Berúthiel is a commander, and apparently her model comes with a Throne? I assuming it is Gondorian, so if nothing it's a good example for how a queen ones look.

![image](https://user-images.githubusercontent.com/79544635/154412123-bc3ec5f2-0bf1-48f2-9f80-059c905c7d53.png)
Berúthiel, black numenorean queen of gondor, an other 2d example of how a gondorian throne for a queen may look.

![image](https://user-images.githubusercontent.com/79544635/154414998-b5d5215c-3ce7-46af-8855-cfd370ac10b1.png)
A generic 2d artwork for a Gondorian and/or Numenorean throne from the game Lord of the Ring: Rise of War main hall

</details>

**Rohan**
So Rohan has it's iconic Throne in Meduseld the great Golden Hall.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/154412499-b3418aa1-5cf1-4f2b-ab37-1c695cd6349c.png)

![image](https://user-images.githubusercontent.com/79544635/154412517-3d3fe982-2951-42e1-bc7d-a9e3f6d5cfdd.png)

![image](https://user-images.githubusercontent.com/79544635/154412524-2c0cbc9d-f12c-47ac-93fd-9827b8f0286d.png)

![image](https://user-images.githubusercontent.com/79544635/154412549-11a41542-14d1-477a-82d8-1a48f29d56b9.png)
So these are just the ones from the movie, but i'm sure there are a lot of other great examples of rohirrim thrones.

</details>

**Isengard**
So I'm guessing Isengard is the least likely to have several courts with it's asset, so maybe not as reusable as other, but still an important iconic setting for lotr.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/154412723-60ec63e1-28f7-44cf-b331-80e09a224e3b.png)
the throne from peter jacksson's setting

![image](https://user-images.githubusercontent.com/79544635/154412786-808985b2-f882-43f1-850a-3a47a625fb50.png)

![image](https://user-images.githubusercontent.com/79544635/154412804-b7989f9a-7843-42cb-9abe-2d8bb8b3235a.png)

![image](https://user-images.githubusercontent.com/79544635/154412821-874f442b-736d-4cb5-88f9-98ec52f7e7d8.png)
WETA designs by games workshop (i think)

![image](https://user-images.githubusercontent.com/79544635/154412871-cbda9800-ef02-46dd-87d1-525f0cc18390.png)
A 2D art of a generic Isengard throne from the mobile game Lord of the Rings: Rise of War.

![image](https://user-images.githubusercontent.com/79544635/154413001-37834857-c9a8-4fb0-9703-0c1b8e38e198.png)

![image](https://user-images.githubusercontent.com/79544635/154413027-bc8be654-68f8-48fb-aafc-f44c16718ae1.png)

![image](https://user-images.githubusercontent.com/79544635/154413066-17e46f19-e967-4feb-b65d-2b85d808bd06.png)

![image](https://user-images.githubusercontent.com/79544635/154413122-89142a24-ae78-4bfd-a5d1-2f89cc1c6e51.png)
So these are from the game Lord of the Ring: Online. And while i personally think the other ones are better, i do think these are good also for it looks very Numenorean. As Orthanc build by the Dúnedain in the second age, so the Numenorean artistic style still lingers heavily, so it could still be a good inspiration for some Dunedain or Black Numenorean throne i think.

</details>

**Mordor**
So While Sauron is probably the main one that uses these, i think most nazguls and orcish Or forces of evil) kingdoms it would also fit for, so having at least a generic mordor throne would be good.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/154413851-13664548-9b50-4db7-897b-f3380d809f68.png)
2d art of Mordor main hall from the game Lord of the ring: Rise of War.

![image](https://user-images.githubusercontent.com/79544635/154413938-84a225da-7a68-4857-befc-f262ad4ab447.png)
A Evil throne room from Middle Earth: Shadow of War. Am not sure from where since i've not played it myself yet.

![image](https://user-images.githubusercontent.com/79544635/154414050-01e48f56-3125-47db-b340-5d23786ad721.png)
So while not exactly Mordor, this is the 2d artwork of the Witch Kings throne while he rules Angmar from the game _Battle for Middle Earth 2 Rise of the Witch King_ and it does still look very much in line of mordors evil style.

</details>

# Suggestions for 3.0 content

So the upcoming 3.0 patch will introduce more courts that needs unique assets.

**Elves**
We will at least get Lothlorien and the woodland realm of Mirkwood, with maybe Avarian elves on that, and more elves coming with 5.0 So having a "generic" elven throne could be good
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/154414555-b9c7ed5b-98cf-4098-911f-7827bbbac272.png)
So incredible bad quality of a 2d artwork picture from the game lord of the ring:rise of war elves main hall. But it gives a generic elven throne vibe. 

![image](https://user-images.githubusercontent.com/79544635/154414703-3fc81eed-dd3c-4979-a2eb-142f78c9585e.png)
the chair used during the council of elrond in rivendell during the decision of what to do with the ring. a variation of this could make a good throne?

![image](https://user-images.githubusercontent.com/79544635/154414810-7ba0d942-7f3b-4013-86f6-4d744ec4547a.png)

![image](https://user-images.githubusercontent.com/79544635/154414839-85092a0b-08f1-4b22-88f1-94c05b3506bc.png)

![image](https://user-images.githubusercontent.com/79544635/154414856-8c29b539-e860-4655-ad9d-d3b12b89d2c3.png)

![image](https://user-images.githubusercontent.com/79544635/154414870-54e84d02-8d4e-48ca-b479-05802e0ee40e.png)
Different pictures of the Throne of Thranduil styled and from the hobbit trilogy

</details>

**Rhûn**
So the easterlings are coming with 3.0 and could be cool for them to get something unique, even though everyone thinks of elves.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/154415198-86d5dc66-72d7-4968-9761-103dcff1af68.png)
A 2d artwork of a Rhûn throne from the game Lord of the Rink: Rise of War, Rhûn main hall pic

![image](https://user-images.githubusercontent.com/79544635/157910400-de1a3c8a-eba5-4cda-af3e-909c9e6f1a9e.png)
Found a clearer picture of the Rhûn throne room

(Update 2022-09-22) 
![image](https://user-images.githubusercontent.com/79544635/191786218-2f855dba-7878-4253-bb37-39b9cc252fd4.png)
A new artwork by LOTR Rise to War on a Rhûn Throne-room with a throne in it :P

</details>

# 4.0
i just had to throw some in.

**Dwarves**
Dwarves!
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/79544635/154415505-f4a4913e-252e-424d-9e41-f3d4c31c3eb4.png)

![image](https://user-images.githubusercontent.com/79544635/154415425-49cf0f95-02e7-4e47-bbed-e701f9fb54b2.png)

![image](https://user-images.githubusercontent.com/79544635/154415447-72d98775-273b-47d0-a30b-ace7e96b9cc0.png)

![image](https://user-images.githubusercontent.com/79544635/154415465-b518fea1-3761-44a5-802b-4c3a6b8fdd61.png)

![image](https://user-images.githubusercontent.com/79544635/154415538-9c3d90f9-c470-4397-9e72-3d6092ba060e.png)
WETA design of Erebors throne

![image](https://user-images.githubusercontent.com/79544635/154415579-2eda0c26-24cb-4261-aa22-3af2348aa38c.png)
the dwarven/erebor generic main hall artwork from Lord of the Ring: Rise of War.

![image](https://user-images.githubusercontent.com/79544635/154415660-65d9a7f8-6b85-4743-a5a9-fef812618a7b.png)

![image](https://user-images.githubusercontent.com/79544635/154415681-a835cc00-f6f7-4aea-9718-3f43d7036fd8.png)
Dwarven throne from the game Lord of the Ring: Online

</details>

**Comment by Remerod** [comment]
Everyone feel free to add more suggestions for thrones! I'm sure i just gotten some of the more easily found ones, and there is a lot in like games as LOTRO and other artwork that could be great examples for the artist! But try to use the [spoiler](https://github.com/MattTheLegoman/RealmsInExile/wiki/Text-Tricks-on-GitHub) feature so the issue will be navigable. ;)

**Comment by Remerod** [comment]
Some more pictures on shadow of War throne rooms (provided by Matt on the discord channel graphics) 
Source: https://alampa.artstation.com/albums/624190

**Comment by jj248** [comment]
This is going to be a low priority behind other 3D work, so pushing to v4.

**Comment by Jaco-Daan** [comment]
Closing this issue as it seems to be more of a suggestion thread? Would be much better if this were placed on DC, while trying to keep Github issues to only things that need to be tracked, such as bugs or In Progress work.
