### ISSUE TITLE
Additional dynasty perk trees

### ISSUE THREAD

**Issue by jj248** [CK3RealmsinExile/RealmsInExile#516]
Consider adding additional dynasty perk trees (e.g. for elves).

**Comment by JukeJukestar** [comment]
Maybe a "Dark" dynasty perk tree for forces of evil that makes dynasty members more adept at sorcery and such?

Im not a huge fan of adding more "X culture" dynasty perk trees such as the haradrim one, but I can see why elves may be an exception. Perk trees should be based around certain archetypes and values your dynasty focuses on, not just your culture and attributes that are associated with it (thats what traditions are for!)

**Comment by jj248** [comment]
Pushing to v3.

**Comment by Jaco-Daan** [comment]
This can be closed. Has already been discussed that we do not want to add more cultural/heritage specific dyansty trees, and instead just have one based on each race. Closing for now
