### ISSUE TITLE
Internal conflict in Dorwinion

### ISSUE THREAD

**Issue by BriceLeduc** [CK3RealmsinExile/RealmsInExile#827]
Dorwinion has little going on right now, we should add internal conflict via events and decisions : Medlo should start influencing pro-Easterling vassals to start factions and assassination plots, with events allowing the Realm-Master to counter them and bring them back to their side. Eventual events for major vassals too.

**Comment by JukeJukestar** [comment]
I hope we can do this via vanilla factions and schemes by just nudging the AI into certain directions with modifiers and events, it'd be sick to have a dynamic murder scheme where its a different vassal every game

**Comment by Remerod** [comment]
> Dorwinion has little going on right now, we should add internal conflict via events and decisions : Medlo should start influencing pro-Easterling vassals to start factions and assassination plots, with events allowing the Realm-Master to counter them and bring them back to their side. Eventual events for major vassals too.

maybe that could be something for Kirun?

**Comment by BriceLeduc** [comment]
> > Dorwinion has little going on right now, we should add internal conflict via events and decisions : Medlo should start influencing pro-Easterling vassals to start factions and assassination plots, with events allowing the Realm-Master to counter them and bring them back to their side. Eventual events for major vassals too.
> 
> maybe that could be something for Kirun?

For who ? It doesn't actually need to be the same vassal every time. We could easily randomise the rebellion leader selection.

**Comment by BriceLeduc** [comment]
Which would make cheesing it a lot more difficult, if you don't know in advance who's going to plot against you

**Comment by Jermanlordy** [comment]
Kirun is the heir of Zhamik the starting Loke Khan of Medlushukain

**Comment by BriceLeduc** [comment]
I'm not sure what he'd be doing there, then. Imo it's going to be the Loke-Kan himself influencing the Dorwinion nobles to create internal trouble. Not an actual Easterling lord doing the job

**Comment by Remerod** [comment]
I always imagine if Kirun ever got more cover in the future he would have his sight on Dorwinion (based on how he kind of has it in lotr: rise to war) So i thought it would make sense for him to have plots there. But it was just a suggestion, not saying it neccesarily needs to be him

**Comment by Jaco-Daan** [comment]
Making a comment here just to remind myself to take a look at this issue after finishing with a few of the other issues i'm currently busy with.

**Comment by Jaco-Daan** [comment]
This is dealt with via the Huz-Margoz chain, as he influences the Dorwinion. While it can still be refined, it _does_ add internal conflict
