### ISSUE TITLE
Aligment doesn't change when provinces are converted

### ISSUE THREAD

**Issue by JukeJukestar** [CK3RealmsinExile/RealmsInExile#868]
We had someone on the discord report that faith alignment (in the mapmode) didnt change when provinces were converted.
However, before we move this to bugs we need further testing and confirmation.

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/7b47006a-383e-49c7-9369-c12273a0d131)
top pic is before I took dol guldur and bottom pic is after I took dol guldur
![image](https://github.com/jj248/RealmsInExile/assets/86676697/2e804fb6-1e89-448f-bf83-1e5fe8f1b02e)
as you can see the alignment has clearly not changed. I even waited a year after I took dol guldur just to see if the map needed time to update

**Comment by Jaco-Daan** [comment]
Can confirm, still doesnt work

**Comment by Jaco-Daan** [comment]
This has been confirmed to work by @Hendrix1337x. Closing
