### ISSUE TITLE
Unlanded human characters in Valinor

### ISSUE THREAD

**Issue by Remerod** [CK3RealmsinExile/RealmsInExile#886]
It's been reported in the bug-report forum that some Unlanded human characters ends up in Valinor, i have doubled checked this and it is indeed so. So this is something that needs tweaking

Vector mentioned this:
> Probably just need to add a courtier cull event for any characters in Valinor on a yearly basis
Any non-Elves get DAS BOOT

![image](https://user-images.githubusercontent.com/79544635/235954817-c48ea6b6-095f-42ac-963e-1237098b7d1c.png)

**Comment by BriceLeduc** [comment]
Probably linked to a missing trigger in an event, ready to test

**Comment by savagesach** [comment]
![image](https://github.com/jj248/RealmsInExile/assets/86676697/6ebc39ce-c719-40ce-a295-a036575aa315)
finarfin's court is still being invaded by gondorians

**Comment by BriceLeduc** [comment]
@Jaco-Daan didn't you solve this ?

**Comment by Jaco-Daan** [comment]
This has been solved. The issue is courtiers not being assigned to ssomeone that is landed at game start

cloosing
