### ISSUE TITLE
Drinking Contest

### ISSUE THREAD

**Issue by BriceLeduc** [CK3RealmsinExile/RealmsInExile#949]
Drinking duel for Dwarves :
Duelling interface, check chess/song battles for code, challenge via character interaction.
Should be available to cultures with a certain tradition, sacred feasts ?
Challenge event should be added to feast pool events for cultures with the relevant tradition, possibly also a hold_court event/court event

**Comment by wFredsch** [comment]
ToDo:
- Character Interaction

**Comment by Jaco-Daan** [comment]
This seems to have bee put on a permanent hold. Closing for now until we choose to pursue this again
